apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.teams: channelName
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: jenkins
    server: 'https://kubernetes.default.svc'
  source:
    path: Applications/Jenkins/charts
    repoURL: 'https://github.com/SambariManikanta09/devops_practice.git'
    targetRevision: apps
    helm:
      valueFiles:
      - values.yaml
  project: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true