replicaCount: 1

image:
  repository: nginx
  tag: "1.19.10"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30005  # Change this to any desired node port within the valid range (30000-32767)

resources: {}
